name: Node.js CI and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run build script if present
      - name: Build
        run: npm run build --if-present

      # Run tests
      - name: Test
        run: npm test

      # Deploy to GitHub Pages (only on push to main, and only for Node.js 20.x to avoid duplicate deployments)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && matrix.node-version == '20.x'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
    - run: npm test
